export const STANDARD_FORM_ACTION_TYPES = {
    INCREMENT_COUNTER: 'INCREMENT_COUNTER',
    DECREMENT_COUNTER: 'DECREMENT_COUNTER',
    CHANGE_VALUE: 'CHANGE_VALUE',
    SET_LOADING: 'SET_LOADING',
    SET_LOADED: 'SET_LOADED',
    RESET: 'RESET'
}