export const STANDARD_FORM_ACTION_TYPES = {
    INCREMENT_COUNTER: 'INCREMENT_COUNTER',
    DECREMENT_COUNTER: 'DECREMENT_COUNTER',
    CHANGE_VALUE: 'CHANGE_VALUE',
    FOCUS_TEXTAREA: 'FOCUS_TEXTAREA',
    IS_LOADING: 'IS_LOADING',
    IS_LOADED: 'IS_LOADED',
    RESET: 'RESET'
}